export const changeAddStatusMap=(addPopupVisible)=>({type:'changeAddStatus',addPopupVisible})
export const getEmployeeListMap=(employeeList)=>({type:'getEmployeeList',employeeList})
export const changeUpdateStatusMap=(updatePopupVisible)=>({type:'changeUpdateStatus',updatePopupVisible})
export const getChooseValueMap=(chooseValue)=>({type:'getChooseValue',chooseValue})
export const setCheckValueMap=(checkValue)=>({type:'setCheckValue',checkValue})
export const setPopPassWordMap=(popPassWordValue)=>({type:'popNameAndPassWord',popPassWordValue})
export const changeAddPopStatusMap=(AddPopStatus)=>({type:'changeAddPopStatus',AddPopStatus})
export const getAllOrder=(orderList)=>({type:'getAllOrder',orderList})

export const getAllUseableParkingBoy=(parkingBoyList)=>({type:'getAllUseableParkingBoy',parkingBoyList})
export const getChooseOrderRecord=(orderRecord)=>({type:'getChooseOrderRecord',orderRecord})
export const getParkingBoyRecord=(parkingBoyRecord)=>({type:'getParkingBoyRecord',parkingBoyRecord})
export const changePopupVisibleValue=(visibleValue)=>({type:'changePopupVisibleValue',visibleValue})
export const assignOrder1=(orderList)=>({type:'assignOrder',orderList})
